services:
  floci-gcp:
    build:
      context: .
      dockerfile: docker/Dockerfile.jvm-package
    tty: true
    ports:
      - "4588:4588"
    volumes:
      - ./data:/app/data
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      FLOCI_GCP_HOSTNAME: floci-gcp
      FLOCI_GCP_BASE_URL: http://floci-gcp:4588
    networks:
      floci_gcp_default:
        aliases:
          - localhost.floci.io

networks:
  floci_gcp_default:
    name: floci_gcp_default
