quarkus:
  log:
    console:
      format: "%d{yyyy-MM-dd HH:mm:ss,SSS} %-5p [%c{3.}] %s%e%n"
      async:
        enabled: true
        overflow: block
        queue-length: 512

  http:
    port: ${floci-gcp.port}
    host: 0.0.0.0
    http2: true
    limits:
      max-body-size: ${floci-gcp.max-request-size}M

  grpc:
    server:
      use-separate-server: false

  shutdown:
    delay-enabled: true

  native:
    additional-build-args:
      - --report-unsupported-elements-at-runtime
      - --allow-incomplete-classpath
      - --enable-url-protocols=http,https
      - --initialize-at-run-time=com.github.dockerjava.transport.NamedPipeSocket$Kernel32

floci-gcp:
  port: 4588
  max-request-size: 512
  base-url: "http://localhost:4588"
  default-project-id: floci-local
  storage:
    mode: memory
    persistent-path: ./data
    host-persistent-path: ./data
    prune-volumes-on-delete: false
    wal:
      compaction-interval-ms: 30000
  services:
    gcs:
      enabled: true
    pubsub:
      enabled: true
    firestore:
      enabled: true
    datastore:
      enabled: true
    iam:
      enabled: true
    secretmanager:
      enabled: true
    kafka:
      enabled: true
      mock: false
      default-image: "redpandadata/redpanda:latest"
    cloudtasks:
      enabled: true
    cloudrun:
      enabled: true
      execution:
        enabled: false
        mock: false
        default-port: 8080
        startup-timeout: 240s
        request-timeout: 300s
        operation-timeout: 300s
        cleanup-timeout: 15s
        container-name-prefix: floci-cloudrun
        url-host-suffix:
    cloudfunctions:
      enabled: true
  dns:
    extra-suffixes:
  docker:
    log-max-size: "10m"
    log-max-file: "3"
    docker-host: "unix:///var/run/docker.sock"
  init-hooks:
    shell-executable: /bin/sh
    shutdown-grace-period-seconds: 2
    timeout-seconds: 30
